### ISSUE TITLE
Error screen "Failed to initialize player" shown even after network is active

### ISSUE THREAD

**Issue by numberlock11** [vmware/replay-app-for-tvos#1]
Once network is disconnected and then resumed back, video plays in the background but the error screen is visible.

<img width="1680" alt="screen shot 2017-08-24 at 8 54 43 pm" src="https://user-images.githubusercontent.com/13529542/29695075-7e61214c-890e-11e7-9a80-a14f06e83028.png">

**Comment by rajivsingh0902** [comment]
Fixed in commit 73daf1e9289b9e84b32105b34f1c403bc3098ae7
