### ISSUE TITLE
Cached video does not loop

### ISSUE THREAD

**Issue by numberlock11** [vmware/replay-app-for-tvos#2]
Steps of reproduction:

1) Allow the video to run once completely
2) After the video starts to loop, disconnect network. Video continues to play with the cached version
3) Once the cached video is complete and needs to loop back, it throws the "Failed to initialize" error and video does not loop

**Comment by rajivsingh0902** [comment]
Fixed in commit d70c386df19f5dba1e16102ec1a5e993ba14e5e6
